DROP TABLE IF EXISTS `parcels`;

CREATE TABLE `parcels` (
  `ogc_fid` serial comment 'object id',
  `geoid` text comment 'FIPS code',
  `sourceagent` text comment 'Source Agent',
  `parcelnumb` text comment 'Parcel ID',
  `usecode` text comment 'Parcel Use Code',
  `usedesc` text comment 'Parcel Use Description',
  `zoning` text comment 'Zoning Code',
  `zoning_description` text comment 'Zoning description',
  `struct` boolean comment 'Structure on Parcel',
  `multistruct` boolean comment 'Multiple structures on Parcel',
  `structno` int comment 'Number of structures on parcel',
  `yearbuilt` int(4) comment 'Structure Year Built',
  `numstories` double precision comment 'Number of Stories',
  `numunits` smallint unsigned comment 'Number of Units',
  `structstyle` text comment 'Structure Style',
  `parvaltype` text comment 'Parcel Value Type',
  `improvval` double precision comment 'Improvement Value',
  `landval` double precision comment 'Land Value',
  `parval` double precision comment 'Total Parcel Value',
  `agval` double precision comment 'Agricultural Value',
  `saleprice` double precision comment 'Last sale price',
  `saledate` date comment 'Last sale date',
  `taxamt` double precision comment 'Annual Tax Bill',
  `taxyear` text comment 'A county provided attribute indicating the tax year the assessor data applies to',
  `owntype` text comment 'Owner Type',
  `owner` text comment 'Owner Name',
  `ownfrst` text comment 'Owner First Name',
  `ownlast` text comment 'Owner Last Name',
  `owner2` text comment 'Second Owner Name',
  `owner3` text comment 'Third Owner Name',
  `owner4` text comment 'Fourth Owner Name',
  `subsurfown` text comment 'Subsurface Owner',
  `subowntype` text comment 'Subsurface Owner Type',
  `mailadd` text comment 'Mailing Address',
  `mail_address2` text comment 'Mailing Address Second Line',
  `careof` text comment 'Mailing Address Care of',
  `mail_addno` text comment 'Mailing Address Street Number',
  `mail_addpref` text comment 'Mailing Address Street Prefix',
  `mail_addstr` text comment 'Mailing Address Street Name',
  `mail_addsttyp` text comment 'Mailing Address Street Type',
  `mail_addstsuf` text comment 'Mailing Address Street Suffix',
  `mail_unit` text comment 'Mailing Address Unit Number',
  `mail_city` text comment 'Mailing Address City',
  `mail_state2` text comment 'Mailing Address State',
  `mail_zip` text comment 'Mailing Address ZIP Code',
  `mail_country` text comment 'Mailing Address Country',
  `mail_urbanization` text comment 'Mailing Address Urbanizacion (Puerto Rico)',
  `address` text comment 'Parcel Address',
  `address2` text comment 'Parcel Address Second Line',
  `saddno` text comment 'Parcel Address Number',
  `saddpref` text comment 'Parcel Address Prefix',
  `saddstr` text comment 'Parcel Address Street Name',
  `saddsttyp` text comment 'Parcel Address Street Type',
  `saddstsuf` text comment 'Parcel Address Street Suffix',
  `sunit` text comment 'Parcel Address Unit',
  `scity` text comment 'Parcel Address City',
  `original_address` text comment 'Address fields as originally provided by the county, separated by a semicolon and a space',
  `city` text comment 'US Census County Subdivision',
  `county` text comment 'Parcel Address County',
  `state2` text comment 'Parcel Address State',
  `szip` text comment 'Parcel Address Zip Code',
  `urbanization` text comment 'A postal address field commonly used in Puerto Rico',
  `location_name` text comment 'Location Name',
  `address_source` text comment 'Primary Address Source',
  `legaldesc` text comment 'Legal Description',
  `plat` text comment 'Plat number the parcel is recorded on',
  `book` text comment 'Book/Liber the parcel is recorded in',
  `page` text comment 'Page/Folio the parcel is recorded on',
  `block` text comment 'Block',
  `lot` text comment 'Lot',
  `neighborhood` text comment 'Neighborhood',
  `subdivision` text comment 'Subdivision',
  `lat` text comment 'On parcel centroid latitude decimal coordinate',
  `lon` text comment 'On parcel centroid longitude decimal coordinate',
  `goz` text comment 'Federal Qualified Opportunity Zone',
  `goz_tract` text comment 'Qualified Opportunity Zone Tract Number',
  `census_tract` text comment 'Census 2010 Tract',
  `census_block` text comment 'Census 2010 Block',
  `census_blockgroup` text comment 'Census 2010 Blockgroup',
  `sourceref` text comment 'A county provided reference for the parcel record',
  `sourcedate` date comment 'A county provided date for the parcel record',
  `sourceurl` text comment 'A county provided url to the county parcel record online',
  `recrdareatx` text comment 'Recorded Area (text)',
  `recrdareano` double precision comment 'Recorded Area (number)',
  `gisacre` double precision comment 'County-provided Acres',
  `sqft` double precision comment 'County-provided Parcel Square Feet',
  `ll_gisacre` double precision comment 'Loveland calculated parcel areas',
  `ll_gissqft` bigint comment 'Loveland calculated parcel square feet',
  `ll_bldg_footprint_sqft` int comment 'Loveland calculated building footprint square feet',
  `ll_bldg_count` int comment 'Total number of buildings on the parcel, calculated by loveland',
  `cdl_raw` text comment 'Cropland Data Layer raw values',
  `cdl_majority_category` text comment 'This is the human readable Category name for the land cover type that is most common on the parcel',
  `cdl_majority_percent` double precision comment 'This is the actual percentage of pixels for the majority category',
  `cdl_date` text comment 'The year of the Cropland Data Layer data set the current attributes are derived from',
  `revisedate` date comment 'The last date of last revision as provided by the county assessors office if available',
  `path` text comment 'Lovelands human-readable identifier for this parcel. Not guaranteed to be stable between updates',
  `ll_stable_id` text comment 'Stable ID Status',
  `ll_uuid` varchar(36) comment 'Uniquely identifies a single parcel with a v4 uuid. A stable parcel id across county data refreshes. This field should be used for tracking indiviual parcels.',
  `ll_updated_at` timestamp comment 'Timestamp of last update of any kind to this row, internal changes to row, and/or county updates',
  `dpv_status` text comment 'USPS Delivary Point Validation',
  `dpv_codes` text comment 'Delivery Point Validation Codes',
  `dpv_notes` text comment 'Delivery Point Validation Notes',
  `dpv_type` text comment 'Delivery Point Match Type',
  `cass_errorno` text comment 'CASS Error Codes',
  `rdi` text comment 'Residential Delivary Indicator',
  `usps_vacancy` text comment 'USPS Vacancy Indicator',
  `usps_vacancy_date` date comment 'USPS Vacancy Indicator Date',
  `lbcs_activity` numeric comment 'Land Use Code: Activity',
  `lbcs_activity_desc` text comment 'Land Use Code Description: Activity',
  `lbcs_function` numeric comment 'Land Use Code: Function',
  `lbcs_function_desc` text comment 'Land Use Code Description: Function',
  `lbcs_structure` numeric comment 'Land Use Code: Structure',
  `lbcs_structure_desc` text comment 'Land Use Code Description: Structure',
  `lbcs_site` numeric comment 'Land Use Code: Site',
  `lbcs_site_desc` text comment 'Land Use Code Description: Site',
  `lbcs_ownership` numeric comment 'Land Use Code: Ownership',
  `lbcs_ownership_desc` text comment 'Land Use Code Description: Ownership',
  PRIMARY KEY (`ogc_fid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
